
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1USXhOekU1TURVME1Gb1hEVE15TVRJeE5ERTVNRFUwTUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDdjCmVjVE90QTFVRFM4UWh6QkQvMFZ1bzZVMEZNTDBCNnhDbCtDZm5MN2huaDAwMWRLeE5hMkJmYndZUmZURmxDNGYKUWxOUmNuaWF1K1JxSGFmZkgxOGRGblgzeHBGc1pscDRRR0VaT20wRExrcThkOTR6aHpnb3djZnI2ZmF2NnpOaAp6SlRzZUdFb2ZrZVhSRi8xZ2RxeXdqSHF4WDZhSndmUWVpaWk4a2VHL1g4S3ZwRjRVZ0Fwcmx6VUNUVnBQTVJYCmtzMGtQVFJBQU1wODkyVGVHcHVoUWxhZFh6VjAvNkJDSW9WZHFoeVdLWGJmc1FhNmpYTU11VEladmZtbU1XSWIKUjJGdkhDZGVUOWk1Y0FwcnVaeG5qMWRpb2h5aVBMK1Y3TW9ic0dHdlRiT200Y3lxYkxLRWs0VEp0WkJ0bmh4MApjaWI2R0ZTdU5INUVaL01mOU5FQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZIcjJsUE1ldkR0UkxNaHdlVVlITjR4ZTZFajVNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSWZzODUwYkd3KzRDTUhDeW9sMgpUd1hTK0lzZncrMEJQMkRKNWQ3VzFIbGNucUdIcDhEYktGRlBTcXVuR05hN3RnOTVyb2FER09nUDBKOTlDZEo0CmlWdy9DdXlnVFJtZDBzZlNZYlFHK1JhTDVOdW9HQ01nb0hZWkZuS3J4d2RqTjYzaXlCdzFzR1VzRFVpcmxoTm4KRko3aE93ZlFwRFJJSzBSMW9JRzBYK2k3TndUSWplN0RDMCtWbEtjbGY2MFdkS3pGVkYrRW82TG1NL3pKV3U4ZgpkdWMwcklucTNJMTk3ZnlwZ3M5SFY4eEFCdTFLTENrZkVoNDY4UFFabDRIaXY1cEZhWVdLRFZBSG9tYXVpNE5rCnN0QTZqNkZ5YlhMTUpVTUJFdHg2c2JDeDRrRytrbnNiNXExVEM2V0VSYjVTaEViRXc0STBUZ3hReTRuSUQ3SHkKUjRnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://2d6df030-2d7c-4c6a-a14f-34f4092c9461.us-west-1.linodelke.net:443
  name: lke84165

users:
- name: lke84165-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImVzamZJSWxiSzNqMHRnSVpqNHJwNjhJUkp2OG9jN3F6d29NTUE2dHNZamsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tenRiengiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNTI3ZWZlZDktYWFiNy00MGQ3LWIwYzktNWM0OWRlM2I5MzE0Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.c5gfRHBZTIXP9n3QCUKnxCU1jQYE5yvq1cfhCpS5Zv_UuW8ui5bx5rXSf8hIcP84oO6M0hUSUJ4igZXWzHeG47D8-j5YMKud3KYDoAOWma6JfiRNv8Sr7c6tK-vZ_OqfOMi49puKEwCR7AFRVYeV6HVSJi2RuVZZ244YZoQTGtrwvyNkvUlYXbLRQ4iw-xDlFgFzmjRki1pqvBS49J8E2wWNknFfGvQpErGoWLo44KzVXs8vpfggUhNP6qw_RuFXOxNiNaUvoxgyiPx8gVWwyokMn88dO7Vj151OyGU9jdWdAuyycl791CcogrtLMJr_daq64VroLAMRZ-iYLoWz9Q

contexts:
- context:
    cluster: lke84165
    namespace: default
    user: lke84165-admin
  name: lke84165-ctx

current-context: lke84165-ctx
